// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egsykgmukpshizgjmjdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnc3lrZ211a3BzaGl6Z2ptamRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTkyNzgsImV4cCI6MjA2ODk5NTI3OH0.w4f2qTO_PXUA3gV2SsZQ07TRPSgyjAilJlByEwr_ewg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});